#define MINDFORGER_VERSION_MAJOR "2"
#define MINDFORGER_VERSION_MINOR "0"
#define MINDFORGER_VERSION_REVISION "0"
#define MINDFORGER_VERSION_STRING "2.0.0"
#define MINDFORGER_VERSION_DWORD 2,0,0,2
#define MINDFORGER_APP_NAME   "MindForger"
#define MINDFORGER_APP_DESCRIPTION  "MindForger Thinking Notebook"
#define MINDFORGER_APP_AUTHOR "Martin Dvorak"
#define MINDFORGER_APP_URL "https://www.mindforger.com"
#define MINDFORGER_APP_COMPANY   MINDFORGER_APP_NAME
#define MINDFORGER_APP_LEGAL "\xA9 2016-2023 Martin Dvorak. All Rights Reserved"
#define MINDFORGER_APP_EXE "mindforger.exe"
