#define MINDFORGER_VERSION_MAJOR "1"
#define MINDFORGER_VERSION_MINOR "55"
#define MINDFORGER_VERSION_REVISION "0"
#define MINDFORGER_VERSION_STRING "1.55.0"
#define MINDFORGER_VERSION_DWORD 1,55,0,2
#define MINDFORGER_APP_NAME   "MindForger"
#define MINDFORGER_APP_DESCRIPTION  "MindForger Thinking Notebook"
#define MINDFORGER_APP_AUTHOR "Martin Dvorak"
#define MINDFORGER_APP_URL "https://www.mindforger.com"
#define MINDFORGER_APP_COMPANY   MINDFORGER_APP_NAME
#define MINDFORGER_APP_LEGAL "\xA9 2016-2022 Martin Dvorak. All Rights Reserved"
#define MINDFORGER_APP_EXE "mindforger.exe" 
